[package]
org = "ballerina"
name = "xslt"
version = "2.3.0"
authors = ["Ballerina"]
keywords = ["xslt", "xml", "html", "xsl", "transformation"]
repository = "https://github.com/ballerina-platform/module-ballerina-xslt"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.3.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "xslt-native"
version = "2.3.0"
path = "../native/build/libs/xslt-native-2.3.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/jakarta.activation-1.2.2.jar"
version = "1.2.2"

[[platform.java11.dependency]]
path = "./lib/saxon-8.9.jar"
version = "8.9"
